#!/usr/bin/env bash
# Track B start-of-clock snapshot.
# Emits a Markdown result file capturing the start timestamp, Hyperliquid
# funding rates per gate-002 universe, and a coarse regime read from BTC
# 4h SMA-180 slope. Pipe stdout to a result file in live/wiki/results/.

set -euo pipefail

API="https://api.hyperliquid.xyz/info"
PAIRS=(BTC ETH SOL DOGE AVAX ARB)
NOW_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- regime read: BTC 4h close series, SMA-180, slope ----------------------
end_ms=$(( $(date +%s) * 1000 ))
start_ms=$(( end_ms - 200 * 4 * 3600 * 1000 ))   # 200 × 4h
btc_json="$(curl -fsS -X POST "${API}" \
  -H 'content-type: application/json' \
  -d "{\"type\":\"candleSnapshot\",\"req\":{\"coin\":\"BTC\",\"interval\":\"4h\",\"startTime\":${start_ms},\"endTime\":${end_ms}}}")"

regime="$(python3 - <<PY
import json, sys
candles = json.loads("""${btc_json}""")
closes = [float(c["c"]) for c in candles][-200:]
if len(closes) < 181:
    print("insufficient-data")
    sys.exit(0)
sma_now  = sum(closes[-180:]) / 180
sma_prev = sum(closes[-181:-1]) / 180
slope_pct = (sma_now - sma_prev) / sma_prev * 100
last = closes[-1]
above = last > sma_now
if slope_pct > 0.05 and above:
    label = "bull"
elif slope_pct < -0.05 and not above:
    label = "bear"
else:
    label = "chop"
print(f"{label}|last={last:.2f}|sma180={sma_now:.2f}|slope_pct={slope_pct:+.3f}")
PY
)"

# --- funding rates ----------------------------------------------------------
meta_json="$(curl -fsS -X POST "${API}" -H 'content-type: application/json' -d '{"type":"metaAndAssetCtxs"}')"

funding_table="$(python3 - <<PY
import json
universe, ctx = json.loads("""${meta_json}""")
names = [u["name"] for u in universe["universe"]]
ctxs  = {names[i]: ctx[i] for i in range(len(names))}
pairs = "${PAIRS[*]}".split()
print("| Pair | mark | funding (hourly) | annualised |")
print("|------|------|------------------|------------|")
for p in pairs:
    if p not in ctxs:
        print(f"| {p}/USDC | n/a | n/a | n/a |")
        continue
    c = ctxs[p]
    mark = float(c["markPx"])
    f    = float(c["funding"])           # hourly on Hyperliquid
    print(f"| {p}/USDC | {mark:,.2f} | {f:+.6f} | {f * 24 * 365 * 100:+.2f}% |")
PY
)"

# --- emit result file -------------------------------------------------------
cat <<MD
# Track B — 30d Hyperliquid dry-run START

**Start timestamp (UTC):** ${NOW_UTC}
**Gate:** [live/wiki/decisions/002-track-b-gate.md](../decisions/002-track-b-gate.md) (BINDING 2026-05-20)
**Strategy:** \`HmmSmaSlopeV2\` @ commit \`9d0fb9b\` (in-repo pin)
**Wallet:** \$1000 simulated, \$200/pair, \`dry_run=true\`, Hyperliquid mainnet prices

## BTC regime at start

\`\`\`
${regime}
\`\`\`

Bands (4h close, SMA-180): bull if slope > +0.05%/period **and** close above SMA; bear if slope < −0.05%/period **and** below SMA; chop otherwise.

## Initial funding rates (per-asset, Hyperliquid mainnet)

${funding_table}

## Pre-registered observables (filled in after 30d)

| Gate criterion         | Threshold                | Result @ T+30d |
|------------------------|--------------------------|----------------|
| Uptime                 | > 99% of 30d             |                |
| Signal fidelity vs BT  | ≥ 95% same-OHLC matches  |                |
| Slippage realism       | ≤ 2× modelled            |                |
| MDD                    | < 8%                     |                |
| Trade count            | ≥ 5 round-trip           |                |
| Funding net            | within ±50bps of model   |                |
| Unhandled exceptions   | 0                        |                |

End-of-clock summary lands in \`live/wiki/results/$(date -u -d '+30 days' +%Y-%m-%d 2>/dev/null || date -u -v+30d +%Y-%m-%d)-hl-paper-end.md\`.

## Generated by

\`live/ops/snapshot.sh\` on ${NOW_UTC}.
MD
